/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AttributeAssignmentExpression } from './attributeAssignmentExpression';

export class AdviceExpression {
    /**
    * Attribute assignment expressions
    */
    'attributeAssignmentExpressions': Array<AttributeAssignmentExpression>;
    /**
    * Advice ID
    */
    'adviceId': string;
    /**
    * Applies to
    */
    'appliesTo': AdviceExpression.AppliesToEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributeAssignmentExpressions",
            "baseName": "attributeAssignmentExpressions",
            "type": "Array<AttributeAssignmentExpression>"
        },
        {
            "name": "adviceId",
            "baseName": "adviceId",
            "type": "string"
        },
        {
            "name": "appliesTo",
            "baseName": "appliesTo",
            "type": "AdviceExpression.AppliesToEnum"
        }    ];

    static getAttributeTypeMap() {
        return AdviceExpression.attributeTypeMap;
    }
}

export namespace AdviceExpression {
    export enum AppliesToEnum {
        Permit = <any> 'PERMIT',
        Deny = <any> 'DENY'
    }
}
