/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Can be null
*/
export class AttributeSelectorType {
    /**
    * Category
    */
    'category': string;
    /**
    * Context selector ID
    */
    'contextSelectorId': string;
    /**
    * Path
    */
    'path': string;
    /**
    * Data type
    */
    'dataType': string;
    /**
    * Must be present
    */
    'mustBePresent': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "contextSelectorId",
            "baseName": "contextSelectorId",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "dataType",
            "baseName": "dataType",
            "type": "string"
        },
        {
            "name": "mustBePresent",
            "baseName": "mustBePresent",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AttributeSelectorType.attributeTypeMap;
    }
}

