/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AttributeValueType {
    /**
    * Content
    */
    'content': Array<string>;
    /**
    * Data type
    */
    'dataType': string;
    /**
    * Other attributes. Can be null
    */
    'otherAttributes': { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "Array<string>"
        },
        {
            "name": "dataType",
            "baseName": "dataType",
            "type": "string"
        },
        {
            "name": "otherAttributes",
            "baseName": "otherAttributes",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return AttributeValueType.attributeTypeMap;
    }
}

