/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AttributeAssignmentExpression {
    /**
    * Expression. Can be null
    */
    'expression': string;
    /**
    * Attribute ID
    */
    'attributeId': string;
    /**
    * Category
    */
    'category': string;
    /**
    * Issuer
    */
    'issuer': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expression",
            "baseName": "expression",
            "type": "string"
        },
        {
            "name": "attributeId",
            "baseName": "attributeId",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AttributeAssignmentExpression.attributeTypeMap;
    }
}

