/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AttributeValueType } from './attributeValueType';

export class Attribute {
    /**
    * Attribute values
    */
    'attributeValues': Array<AttributeValueType>;
    /**
    * Attribute ID
    */
    'attributeId': string;
    /**
    * Issuer
    */
    'issuer': string;
    /**
    * Include in result
    */
    'includeInResult': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributeValues",
            "baseName": "attributeValues",
            "type": "Array<AttributeValueType>"
        },
        {
            "name": "attributeId",
            "baseName": "attributeId",
            "type": "string"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "includeInResult",
            "baseName": "includeInResult",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Attribute.attributeTypeMap;
    }
}

