/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AttributeAssignmentExpression } from './attributeAssignmentExpression';

export class ObligationExpression {
    /**
    * Attribute assignment expressions
    */
    'attributeAssignmentExpressions': Array<AttributeAssignmentExpression>;
    /**
    * Obligation ID
    */
    'obligationId': string;
    /**
    * Fulfill on
    */
    'fulfillOn': ObligationExpression.FulfillOnEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributeAssignmentExpressions",
            "baseName": "attributeAssignmentExpressions",
            "type": "Array<AttributeAssignmentExpression>"
        },
        {
            "name": "obligationId",
            "baseName": "obligationId",
            "type": "string"
        },
        {
            "name": "fulfillOn",
            "baseName": "fulfillOn",
            "type": "ObligationExpression.FulfillOnEnum"
        }    ];

    static getAttributeTypeMap() {
        return ObligationExpression.attributeTypeMap;
    }
}

export namespace ObligationExpression {
    export enum FulfillOnEnum {
        Permit = <any> 'PERMIT',
        Deny = <any> 'DENY'
    }
}
