/**
 * Policy Tool Service
 * Policy Tool Service Swagger Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soultos@protonmail.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Attribute } from './attribute';
import { Content } from './content';

/**
* Can be null
*/
export class PolicyIssuer {
    'content': Content;
    /**
    * Attributes
    */
    'attributes': Array<Attribute>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "Content"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<Attribute>"
        }    ];

    static getAttributeTypeMap() {
        return PolicyIssuer.attributeTypeMap;
    }
}

